name: build-actions
run-name: Build all actions
on:
  push:
    paths:
      - 'git-changelog-generator/**'
      - 'libs/**'
      - 'bump-version/**'
      - '.github/workflows/build-actions.yaml'
  workflow_dispatch:
jobs:
  build-actions:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      # Github Actions run with Node 16 for now, so we must build with Node 16
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: "sudo apt-get install -y libkrb5-dev curl libcurl4 libssl-dev"
      - uses: actions/cache@v3
        name: "Cache npm packages"
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-packages
      - uses: actions/cache@v3
        name: "Cache nodegit"
        with:
          path: libs/node_modules/nodegit
          key: ${{ runner.os }}-nodegit
        # Libs module has all versions fixed, so we can run npm install instead of npm ci, which uses
        # cached version of the node git
      - run: "npm install"
        working-directory: ./libs
        # Hack: because nodegit install takes forever, copy it from one lib to another
      - run: "mkdir git-changelog-generator/node_modules"
      - run: "cp -r libs/node_modules/nodegit git-changelog-generator/node_modules/"
      
      - run: "mkdir bump-version/node_modules"
      - run: "cp -r libs/node_modules/nodegit bump-version/node_modules/"
      - run: "npm install"
        working-directory: ./git-changelog-generator
      - run: "npm run all"
        working-directory: ./git-changelog-generator
      
      - run: "npm install"
        working-directory: ./bump-version
      - run: "npm run all"
        working-directory: ./bump-version
      - run: 'git config --global user.email "ci@inova.si"'
      - run: 'git config --global user.name "Build"'
      - run: 'git add git-changelog-generator/dist/\*'

      - run: 'git add bump-version/dist/\*'
      - run: 'git commit -m "ci: build actions" || true'
      - run: 'git push'
